#!/bin/bash
 
export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"
 
if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
	echo 'Installing Composer'
    	curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR
else
	echo 'Updating Composer'
	php $OPENSHIFT_DATA_DIR/composer.phar -q --no-ansi self-update
fi

if [ -d "$OPENSHIFT_REPO_DIR/php" ]; then
	echo 'Removing php directory'
	rm -rf $OPENSHIFT_REPO_DIR/php
	echo 'Creating symlink for public directory'
	ln -s $OPENSHIFT_REPO_DIR/public $OPENSHIFT_REPO_DIR/php
fi
 echo 'Installing/Updating Composer dependencies'
( unset GIT_DIR ; cd $OPENSHIFT_REPO_DIR ; php $OPENSHIFT_DATA_DIR/composer.phar -q --no-ansi install )

