#!/bin/bash
 
export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"
 
if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
    curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR
else
	php $OPENSHIFT_DATA_DIR/composer.phar -q --no-ansi self-update
fi

if [ -d "$OPENSHIFT_REPO_DIR/php" ]; then
	rm -rf $OPENSHIFT_REPO_DIR/php
	ln -s $OPENSHIFT_REPO_DIR/public $OPENSHIFT_REPO_DIR/php
fi
 
( unset GIT_DIR ; cd $OPENSHIFT_REPO_DIR ; php $OPENSHIFT_DATA_DIR/composer.phar -q --no-ansi install )

